package obs_test

import (
	"context"
	"regexp"
	"strings"
	"testing"

	"github.com/zanehu-ai/x-go/obs"
)

// ── Request-ID ────────────────────────────────────────────────────────────────

func TestRequestIDRoundTrip(t *testing.T) {
	ctx := obs.WithRequestID(context.Background(), "abc-123")
	got, ok := obs.RequestIDFromContext(ctx)
	if !ok {
		t.Fatal("RequestIDFromContext: expected ok=true")
	}
	if got != "abc-123" {
		t.Errorf("got %q, want abc-123", got)
	}
}

func TestRequestIDFromContext_Missing(t *testing.T) {
	_, ok := obs.RequestIDFromContext(context.Background())
	if ok {
		t.Error("expected ok=false for empty context")
	}
}

// TestRequestIDFromContext_EmptyString 空字符串视为缺失。
func TestRequestIDFromContext_EmptyString(t *testing.T) {
	ctx := obs.WithRequestID(context.Background(), "")
	_, ok := obs.RequestIDFromContext(ctx)
	if ok {
		t.Error("empty string should be treated as missing (ok=false)")
	}
}

// ── Tenant-ID ─────────────────────────────────────────────────────────────────

func TestTenantIDRoundTrip(t *testing.T) {
	ctx := obs.WithTenantID(context.Background(), 777)
	got, ok := obs.TenantIDFromContext(ctx)
	if !ok {
		t.Fatal("TenantIDFromContext: expected ok=true")
	}
	if got != 777 {
		t.Errorf("got %d, want 777", got)
	}
}

func TestTenantIDFromContext_Missing(t *testing.T) {
	_, ok := obs.TenantIDFromContext(context.Background())
	if ok {
		t.Error("expected ok=false for empty context")
	}
}

// ── Principal-ID ──────────────────────────────────────────────────────────────

func TestPrincipalIDRoundTrip(t *testing.T) {
	ctx := obs.WithPrincipalID(context.Background(), 42)
	got, ok := obs.PrincipalIDFromContext(ctx)
	if !ok {
		t.Fatal("PrincipalIDFromContext: expected ok=true")
	}
	if got != 42 {
		t.Errorf("got %d, want 42", got)
	}
}

// ── RequestMetadataFromContext ────────────────────────────────────────────────

func TestRequestMetadataFromContext_AllFields(t *testing.T) {
	ctx := obs.WithRequestID(context.Background(), "req-meta-test")
	ctx = obs.WithTenantID(ctx, 10)
	ctx = obs.WithPrincipalID(ctx, 20)

	m := obs.RequestMetadataFromContext(ctx)
	if m[obs.FieldRequestID] != "req-meta-test" {
		t.Errorf("request_id = %q, want req-meta-test", m[obs.FieldRequestID])
	}
	if m[obs.FieldTenantID] != "10" {
		t.Errorf("tenant_id = %q, want 10", m[obs.FieldTenantID])
	}
	if m[obs.FieldPrincipalID] != "20" {
		t.Errorf("principal_id = %q, want 20", m[obs.FieldPrincipalID])
	}
}

func TestRequestMetadataFromContext_EmptyCtx(t *testing.T) {
	m := obs.RequestMetadataFromContext(context.Background())
	if m == nil {
		t.Fatal("map should never be nil")
	}
	if len(m) != 0 {
		t.Errorf("expected empty map, got %v", m)
	}
}

func TestRequestMetadataFromContext_PartialFields(t *testing.T) {
	ctx := obs.WithRequestID(context.Background(), "only-rid")
	m := obs.RequestMetadataFromContext(ctx)
	if _, ok := m[obs.FieldTenantID]; ok {
		t.Error("tenant_id should not be present when not in ctx")
	}
	if m[obs.FieldRequestID] != "only-rid" {
		t.Errorf("request_id = %q, want only-rid", m[obs.FieldRequestID])
	}
}

// ── UUID format check (UUID v4 generated by middleware) ───────────────────────

var uuidRe = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)

func TestUUIDFormat(t *testing.T) {
	// Simulate what middleware generates (uuid.New().String() is v4)
	// Use a known UUID to validate format only
	testIDs := []string{
		"01960000-0000-7000-8000-000000000001", // v7 style
		"550e8400-e29b-41d4-a716-446655440000", // v4 style
	}
	for _, id := range testIDs {
		normalized := strings.ToLower(id)
		if !uuidRe.MatchString(normalized) {
			t.Errorf("UUID %q does not match expected format", id)
		}
	}
}
